<a href="https://colab.research.google.com/github/anjuunni/Sample/blob/main/MultipleLR.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np
from sklearn import linear_model

In [ ]:
from google.colab import files
uploaded = files.upload()

Saving homeprices.csv to homeprices.csv


In [ ]:
df=pd.read_csv("homeprices.csv")

In [ ]:
df.head()

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       NaN   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000

In [ ]:
import math

median_bedrooms=math.floor(df.bedrooms.median())
                                

In [ ]:
print(median_bedrooms)

4


In [ ]:
df.bedrooms=df.bedrooms.fillna(median_bedrooms)

In [ ]:
reg=linear_model.LinearRegression()

In [ ]:
reg.fit(df[['area','bedrooms','age']],df.price)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [ ]:
reg.coef_

array([  112.06244194, 23388.88007794, -3231.71790863])

In [ ]:
reg.intercept_

221323.00186540396

In [ ]:
reg.predict([[3000,3,40]])

array([498408.25158031])

In [ ]:
112.06244194*3000+ 23388.88007794*3+-3231.71790863*40+221323.00186540396

498408.251574024

In [ ]:
reg.predict([[2500,4,5]])

array([578876.03748933])

In [ ]:
from google.colab import files
uploaded = files.upload()

Saving hiring.csv to hiring (1).csv


In [ ]:
hiring_df=pd.read_csv("hiring.csv")

In [ ]:
hiring_df

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0        NaN                    8.0                           9      50000
1        NaN                    8.0                           6      45000
2       five                    6.0                           7      60000
3        two                   10.0                          10      65000
4      seven                    9.0                           6      70000
5      three                    7.0                          10      62000
6        ten                    NaN                           7      72000
7     eleven                    7.0                           8      80000

In [ ]:
   pip install WordToNum

In [ ]:
from WordToNum.word_to_num import WordToNum

In [ ]:
  wtn = WordToNum()

In [ ]:
hiring_df["experience"] = hiring_df["experience"].replace(np.nan,"zero", regex=True)

In [ ]:
hiring_df

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0       zero                    8.0                           9      50000
1       zero                    8.0                           6      45000
2       five                    6.0                           7      60000
3        two                   10.0                          10      65000
4      seven                    9.0                           6      70000
5      three                    7.0                          10      62000
6        ten                    NaN                           7      72000
7     eleven                    7.0                           8      80000

In [ ]:
hiring_df.experience = hiring_df.experience.apply(w2n.word_to_num)

In [ ]:
median_experience=math.floor(hiring_df.experience.median())

In [ ]:
hiring_df

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0           0                    8.0                           9      50000
1           0                    8.0                           6      45000
2           5                    6.0                           7      60000
3           2                   10.0                          10      65000
4           7                    9.0                           6      70000
5           3                    7.0                          10      62000
6          10                    NaN                           7      72000
7          11                    7.0                           8      80000

In [ ]:
hiring_df["experience"] = hiring_df["experience"].replace(0,median_experience, regex=True)

In [ ]:
hiring_df

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0           4                    8.0                           9      50000
1           4                    8.0                           6      45000
2           5                    6.0                           7      60000
3           2                   10.0                          10      65000
4           7                    9.0                           6      70000
5           3                    7.0                          10      62000
6          10                    NaN                           7      72000
7          11                    7.0                           8      80000

In [ ]:
mean_testscore=math.floor(hiring_df["test_score(out of 10)"].mean())

In [ ]:
hiring_df["test_score(out of 10)"] = hiring_df["test_score(out of 10)"].fillna(mean_testscore)

In [ ]:
hiring_df

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0           4                    8.0                           9      50000
1           4                    8.0                           6      45000
2           5                    6.0                           7      60000
3           2                   10.0                          10      65000
4           7                    9.0                           6      70000
5           3                    7.0                          10      62000
6          10                    7.0                           7      72000
7          11                    7.0                           8      80000

In [ ]:
reg1=linear_model.LinearRegression()

In [ ]:
reg1.fit(hiring_df[['experience','test_score(out of 10)','interview_score(out of 10)']],hiring_df['salary($)'])

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [ ]:
reg1.coef_

array([3536.15177261, 2076.70522401, 3194.04920326])

In [ ]:
reg1.intercept_

1419.5243457194665

In [ ]:
reg1.predict([[2,9,6]])

array([46346.47012659])

In [ ]:
3536.15177261*2+2076.70522401*9+3194.04920326*6+1419.5243457194665

46346.47012658947

In [ ]:
reg1.predict([[12,10,10]])

array([96560.88988979])